language: go

go:
  - 1.15.x
  - 1.16
  - master

before_install:
  - go get -t -v ./...

script:
  - go test -coverpkg=./... -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
