language: go

go:
  - 1.15.x
  - 1.16
  - master

before_install:
  - go get -t -v ./...

script:
  - go test . -coverprofile cover.out.tmp
  - cat cover.out.tmp | grep -v ".pb.go" > cover.out
  - tool cover -func cover.out

after_success:
  - bash <(curl -s https://codecov.io/bash)
